Develop -> Master
deepmarket/PLUTO pull request #55
Opened 2019-05-18 06:45 UTC by samgomena

This will break master but is required to get the changes on my branch (`sgomena/develop`) into `develop` after a faulty PR merge that happened earlier.

Just for clarification, please do not merge this without:
1. Approving the PR
2. Contactinting or confirming the merge with the _author_ of the PR.

2019-05-27 16:31 UTC, payaljoshi0189 commented on test/features/application.feature
> +      # TODO: Have to 'manually' define the `login_window` object here; it should be done automagically
Just a spell change from 'automagically' to 'automatically'

2019-05-27 16:37 UTC, payaljoshi0189 commented on test/steps/step_login.py
> +    QTest.keyClicks(context.login_window.login.username, "samgomena@gmail.com")
A suggestion, could we remove hardcoded value(samgomena@gmail.com) and have it read the value using a variable?

2019-05-27 16:45 UTC, payaljoshi0189 requested changes
I have left a few comments before this is merged.Overall, this looks good.

2019-06-20 16:38 UTC, samgomena commented
Fixes for your comments are coming in across a couple other PR's that have/will be created. Going to close this and re-open once `develop` updated.

2019-06-20 16:38 UTC, closed without merging